FROM nvidia/cuda:9.0-base

RUN apt-get update

# Development Tools
RUN apt-get install -y wget zip sqlite3 libdbd-sqlite3-perl

# Setup some convenient tools/functionalities
RUN wget http://mcx.space/nightly/release/v2020/mcx-linux-x86_64-v2020.zip -O /mcx-linux.zip && \
    unzip /mcx-linux.zip -d /
RUN wget http://kwafoo.coe.neu.edu/mcxone/mcxcloud.txt -O /mcxcloud
RUN chmod +x /mcxcloud

RUN useradd -u 6047 mcxcloud

USER mcxcloud

WORKDIR /data
ENV PATH "${PATH}:.:/mcx/bin/"
CMD [ "mcx" ]
