.\" Manpage for mcxshow.
.\" Contact fangqq@gmail.com to correct errors or typos.
.TH man 7 "08 February 2020" "v2021.2" "v2020" "mcxshow man page"
.SH NAME
mcxshow \- a 3D previewer for MCX/MCXCL/MMC photon transport simulations
.SH SYNOPSIS
mcxshow <-f input.json>
.SH DESCRIPTION
MCX Show is an OpenGL based 3D renderer for previewing photon simulation domain
settings in mcx/mmc. Monte Carlo eXtreme (mcx) and Mesh-based Monte Carlo (mmc) are 
rigirously validated, physically-accurate and GPU-accelerated 3D photon transport 
simulators. The MCX/MMC simulators are developed by Dr. Qianqian Fang at the 
Computational Optics and Translational Imaging (COTI) Lab, at Northeastern 
University, Boston, USA. More details regarding mcx/mmc can be found at http://mcx.space

.SH OPTIONS
If `mcxshow` command is executed without parameter, it opens a blank window, and
user can click on the toolbar to load a .json MCX/MCXCL input file to render.

However, one can also use the below options to load a default input file:

.TP
\fB-f/--json\fR
.TP
Use `-f` or `--json` flag to specify an MCX/MCXCL JSON-based input file.
Specifically, mcxshow looks for the `Shapes` and `Optodes` objects in the
root of the JSON data structure, and plots the 3D domain geometries in an OpenGL
window.

.SH SEE ALSO
mcx(7), mmc(7), mcxcl(7), mcxstudio(7), photon(7), mcxviewer(7)
.SH AUTHOR
Qianqian Fang (q.fang@neu.edu)
